// Mocks generated by Mockito 5.4.4 from annotations
// in project2/test/auth_test/domain_test/usecases_test/login_with_phone_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:project2/features/auth/domain/entities/user_entity.dart' as _i2;
import 'package:project2/features/auth/domain/entities/verification_entities.dart'
    as _i3;
import 'package:project2/features/auth/domain/repositories/auth_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerificationResult_1 extends _i1.SmartFake
    implements _i3.VerificationResult {
  _FakeVerificationResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserEntity> loginWithPhone(
    String? phone,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithPhone,
          [
            phone,
            password,
          ],
        ),
        returnValue: _i5.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #loginWithPhone,
            [
              phone,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i2.UserEntity>);

  @override
  _i5.Future<String> register(
    String? firstName,
    String? middleName,
    String? lastName,
    String? phone,
    String? password,
    String? confirmPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            firstName,
            middleName,
            lastName,
            phone,
            password,
            confirmPassword,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #register,
            [
              firstName,
              middleName,
              lastName,
              phone,
              password,
              confirmPassword,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.UserEntity?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i5.Future<_i2.UserEntity?>.value(),
      ) as _i5.Future<_i2.UserEntity?>);

  @override
  _i5.Future<_i3.VerificationResult> startVerification(String? phone) =>
      (super.noSuchMethod(
        Invocation.method(
          #startVerification,
          [phone],
        ),
        returnValue:
            _i5.Future<_i3.VerificationResult>.value(_FakeVerificationResult_1(
          this,
          Invocation.method(
            #startVerification,
            [phone],
          ),
        )),
      ) as _i5.Future<_i3.VerificationResult>);

  @override
  _i5.Future<void> submitVerification(
    String? token,
    String? pin,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitVerification,
          [
            token,
            pin,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
